name: first github action
on:
   push:
jobs:
  first:
       name: first job
       runs-on: ubuntu-latest
       steps:
         - name: We are using checkout actions
           uses: actions/checkout@v4
         - name: list the files
           run: ls
         - name: show the content inside file
           run: cat index.html