name: create a nginx container and also verify
on:
   push:
jobs:
  stage:
      name: nginx container
      runs-on: ubuntu-latest
      steps:
        - name: pull the image of nginx
          run: docker pull nginx
        - name: crate a container of nginx
          run: docker run -itd --name nginx  nginx
        - name: verify docker container
          run: docker ps 
        - name: verify using curl
          run: curl localhost:80